from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('products/', views.products, name='products'),
    path('products/add/', views.add_product, name='add_product'),
    path('products/edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('products/delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('sales/', views.sales, name='sales'),
    path('sales/add/', views.add_sale, name='add_sale'),
    path('sales/view/<int:sale_id>/', views.view_sale, name='view_sale'),
    path('sales/delete/<int:sale_id>/', views.delete_sale, name='delete_sale'),
    path('inventory/', views.inventory, name='inventory'),
    path('inventory/add/', views.add_inventory, name='add_inventory'),
    path('inventory/view/<int:inventory_id>/', views.view_inventory, name='view_inventory'),
    path('inventory/delete/<int:inventory_id>/', views.delete_inventory, name='delete_inventory'),
    path('employees/', views.employees, name='employees'),
    path('employees/add/', views.add_employee, name='add_employee'),
    path('employees/detail/<int:employee_id>/', views.employee_detail, name='employee_detail'),
    path('employees/edit/<int:employee_id>/', views.edit_employee, name='edit_employee'),
    path('employees/delete/<int:employee_id>/', views.delete_employee, name='delete_employee'),
    path('reports/', views.reports, name='reports'),
    path('settings/', views.settings, name='settings'),
    path('search/', views.search, name='search'),
    path('export/products/', views.export_products, name='export_products'),
    path('export/sales/', views.export_sales, name='export_sales'),
    path('export/inventory/', views.export_inventory, name='export_inventory'),
    path('export/employees/', views.export_employees, name='export_employees'),
    path('api/sales-data/', views.api_sales_data, name='api_sales_data'),
    path('api/employee-performance/', views.api_employee_performance, name='api_employee_performance'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]
