name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Reponi klonlash
      - uses: actions/checkout@v4

      # 2) Python versiyasini o‘rnatish (kesh bilan)
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      # 3) Kutubxonalarni o‘rnatish
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Django migratsiya + test
      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: erp_project.settings      # settings moduliga moslang
        run: |
          python manage.py migrate --noinput
          python manage.py test --verbosity 2
